//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Entities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Entities() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPSMonitoreo.Core.Resources.Entities", typeof(Entities).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Alarmas.
        /// </summary>
        public static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Alarmas / Categoria.
        /// </summary>
        public static string AlarmCategory {
            get {
                return ResourceManager.GetString("AlarmCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Marcas.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Marcas / Categorias.
        /// </summary>
        public static string BrandCategory {
            get {
                return ResourceManager.GetString("BrandCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ciudades.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Paises.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email / Propósitos.
        /// </summary>
        public static string EmailPurpose {
            get {
                return ResourceManager.GetString("EmailPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email / Tipos.
        /// </summary>
        public static string EmailType {
            get {
                return ResourceManager.GetString("EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Entidades.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Entidades / Direcciones / Ubicaciones / Tipos.
        /// </summary>
        public static string EntityAddressLocationType {
            get {
                return ResourceManager.GetString("EntityAddressLocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Entidades / Direcciones / Tipos.
        /// </summary>
        public static string EntityAddressType {
            get {
                return ResourceManager.GetString("EntityAddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Entidades / Areas.
        /// </summary>
        public static string EntityArea {
            get {
                return ResourceManager.GetString("EntityArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Entidades / Categorias.
        /// </summary>
        public static string EntityCategory {
            get {
                return ResourceManager.GetString("EntityCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Entidades / Frentes.
        /// </summary>
        public static string EntityFace {
            get {
                return ResourceManager.GetString("EntityFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Entidades / Identificacion / Tipos.
        /// </summary>
        public static string EntityIdentificationType {
            get {
                return ResourceManager.GetString("EntityIdentificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Entidades / Cargos.
        /// </summary>
        public static string EntityPosition {
            get {
                return ResourceManager.GetString("EntityPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Entidades / Relación / Tipos.
        /// </summary>
        public static string EntityRelationType {
            get {
                return ResourceManager.GetString("EntityRelationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Entidades / Tipos.
        /// </summary>
        public static string EntityType {
            get {
                return ResourceManager.GetString("EntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Equipos.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Equipos / Grupos.
        /// </summary>
        public static string EquipmentGroup {
            get {
                return ResourceManager.GetString("EquipmentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cercas.
        /// </summary>
        public static string Geofence {
            get {
                return ResourceManager.GetString("Geofence", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cercas / Categorias.
        /// </summary>
        public static string GeofenceCategory {
            get {
                return ResourceManager.GetString("GeofenceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cercas / Curvas / Grados.
        /// </summary>
        public static string GeofenceCurveGrade {
            get {
                return ResourceManager.GetString("GeofenceCurveGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cercas / Curvas / Tipos.
        /// </summary>
        public static string GeofenceCurveType {
            get {
                return ResourceManager.GetString("GeofenceCurveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cercas / Pendientes.
        /// </summary>
        public static string GeofenceIncline {
            get {
                return ResourceManager.GetString("GeofenceIncline", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cercas / Pendientes / Grados.
        /// </summary>
        public static string GeofenceInclineGrade {
            get {
                return ResourceManager.GetString("GeofenceInclineGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cercas / Capas.
        /// </summary>
        public static string GeofenceLayer {
            get {
                return ResourceManager.GetString("GeofenceLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cercas / Calzadas.
        /// </summary>
        public static string GeofenceRoadSurface {
            get {
                return ResourceManager.GetString("GeofenceRoadSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cercas / Calzadas / Tipos.
        /// </summary>
        public static string GeofenceRoadSurfaceCondition {
            get {
                return ResourceManager.GetString("GeofenceRoadSurfaceCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cercas / Trazado Via.
        /// </summary>
        public static string GeofenceRoadType {
            get {
                return ResourceManager.GetString("GeofenceRoadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cercas / Formas.
        /// </summary>
        public static string GeofenceShape {
            get {
                return ResourceManager.GetString("GeofenceShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cercas / Trafico / Grado.
        /// </summary>
        public static string GeofenceTrafficGrade {
            get {
                return ResourceManager.GetString("GeofenceTrafficGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Modelos.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Personas / Profesiones.
        /// </summary>
        public static string PersonProfession {
            get {
                return ResourceManager.GetString("PersonProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Personas / Saludos.
        /// </summary>
        public static string PersonSalutation {
            get {
                return ResourceManager.GetString("PersonSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Telefonos / Tipos.
        /// </summary>
        public static string PhoneType {
            get {
                return ResourceManager.GetString("PhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Productos.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Productos / Categorias.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Provincias.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Regiones.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Roles.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rutas.
        /// </summary>
        public static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rutas / Categorias.
        /// </summary>
        public static string RouteCategory {
            get {
                return ResourceManager.GetString("RouteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Trayectos.
        /// </summary>
        public static string RouteCourse {
            get {
                return ResourceManager.GetString("RouteCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rutas / Fases.
        /// </summary>
        public static string RouteFace {
            get {
                return ResourceManager.GetString("RouteFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tramos.
        /// </summary>
        public static string RouteSection {
            get {
                return ResourceManager.GetString("RouteSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tramos / Categorias.
        /// </summary>
        public static string RouteSectionCategory {
            get {
                return ResourceManager.GetString("RouteSectionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Segmentos.
        /// </summary>
        public static string RouteSegment {
            get {
                return ResourceManager.GetString("RouteSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Segmentos / Categorias.
        /// </summary>
        public static string RouteSegmentCategory {
            get {
                return ResourceManager.GetString("RouteSegmentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
