//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALARMAS_VELOCIDAD_RANG_TIEM
    {
        public short ALARMA_VELOCIDAD_ID { get; set; }
        public byte RANGO_MODO { get; set; }
        public byte RANGO_ORDEN { get; set; }
        public byte ORDEN { get; set; }
        public short TIEMPO_DESDE { get; set; }
        public short TIEMPO_HASTA { get; set; }
        public short PUNTOS { get; set; }
        public byte GRADO_ID { get; set; }
        public bool PARPADEANTE { get; set; }
        public bool AUDIBLE { get; set; }
    
        public virtual ALARMAS_GRADOS GRADO { get; set; }
        public virtual ALARMAS_VELOCIDAD_RANG RANGO_VELOCIDAD { get; set; }
    }
}
