//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALARMAS_NIVELES_REL
    {
        public short ALARMA_ID { get; set; }
        public byte NIVEL_ID { get; set; }
        public byte DUMMY { get; set; }
    
        public virtual ALARMAS ALARMAS { get; set; }
        public virtual ALARMAS_NIVELES ALARMAS_NIVELES { get; set; }
    }
}
