//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALARMAS_VELOCIDAD_RANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALARMAS_VELOCIDAD_RANG()
        {
            this.RANGOS_TIEMPOS = new HashSet<ALARMAS_VELOCIDAD_RANG_TIEM>();
        }
    
        public short ALARMA_VELOCIDAD_ID { get; set; }
        public byte MODO { get; set; }
        public byte ORDEN { get; set; }
        public short VELOCIDAD_DESDE { get; set; }
        public short VELOCIDAD_HASTA { get; set; }
    
        public virtual ALARMAS_VELOCIDAD ALARMAS_VELOCIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALARMAS_VELOCIDAD_RANG_TIEM> RANGOS_TIEMPOS { get; set; }
    }
}
