//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERCAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CERCAS()
        {
            this.HIJOS = new HashSet<CERCAS>();
            this.PUNTOS = new HashSet<CERCAS_PUNTOS>();
            this.SEGMENTOS = new HashSet<SEGMENTOS_CERCAS>();
            this.CERCAS_OTRAS = new HashSet<CERCAS>();
            this.ENTIDADES_DIRS = new HashSet<ENTIDADES_DIRS>();
            this.ENTIDADES_DIRS_UBICAS = new HashSet<ENTIDADES_DIRS_UBICAS>();
            this.GPS_MONI_ESTADO = new HashSet<GPS_MONI_ESTADO>();
            this.GPS_ALARMAS = new HashSet<GPS_ALARMAS>();
            this.GPS_EVENTOS = new HashSet<GPS_EVENTOS>();
        }
    
        public int ID { get; set; }
        public string AUXILIAR_ID { get; set; }
        public string DESCRIPCION_LARGA { get; set; }
        public string DESCRIPCION_MED { get; set; }
        public string DESCRIPCION_CORTA { get; set; }
        public string ABREVIACION { get; set; }
        public byte CAPA_ID { get; set; }
        public short CATEGORIA_ID { get; set; }
        public Nullable<int> PADRE_ID { get; set; }
        public byte REGION_ID { get; set; }
        public byte FORMA_ID { get; set; }
        public double VERTICE1_LAT { get; set; }
        public double VERTICE1_LNG { get; set; }
        public double VERTICE2_LAT { get; set; }
        public double VERTICE2_LNG { get; set; }
        public double LAT { get; set; }
        public double RADIO { get; set; }
        public double LNG { get; set; }
        public byte ESTADO_ID { get; set; }
        public Nullable<int> CERCA_ENRUTA_ID { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual CERCAS_CAPAS CAPA { get; set; }
        public virtual CERCAS_CATS CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERCAS> HIJOS { get; set; }
        public virtual CERCAS PADRE { get; set; }
        public virtual CERCAS_FORMAS FORMA { get; set; }
        public virtual REGIONES REGION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERCAS_PUNTOS> PUNTOS { get; set; }
        public virtual CERCAS_ENRUTA ENRUTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEGMENTOS_CERCAS> SEGMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERCAS> CERCAS_OTRAS { get; set; }
        public virtual CERCAS CERCA_ENRUTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_DIRS> ENTIDADES_DIRS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_DIRS_UBICAS> ENTIDADES_DIRS_UBICAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPS_MONI_ESTADO> GPS_MONI_ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPS_ALARMAS> GPS_ALARMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPS_EVENTOS> GPS_EVENTOS { get; set; }
    }
}
