//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERCAS_PUNTOS
    {
        public int CERCA_ID { get; set; }
        public byte NO { get; set; }
        public double LAT { get; set; }
        public double LNG { get; set; }
    
        public virtual CERCAS CERCA { get; set; }
    }
}
