//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADES_NOTIF_ALARMAS_EMS
    {
        public int ALARMAS_NOTIF_ID { get; set; }
        public int EMAIL_ID { get; set; }
        public byte DUMMY { get; set; }
    
        public virtual ENTIDADES_EMAILS ENTIDADES_EMAILS { get; set; }
        public virtual ENTIDADES_NOTIF_ALARMAS ENTIDADES_NOTIF_ALARMAS { get; set; }
    }
}
