//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADES_DIRS_TIPOS_REL
    {
        public int DIRECCION_ID { get; set; }
        public byte TIPO_ID { get; set; }
        public byte DUMMY { get; set; }
    
        public virtual ENTIDADES_DIRS DIRECCION { get; set; }
        public virtual ENTIDADES_DIRS_TIPOS TIPO { get; set; }
    }
}
