//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADES_PERSONA
    {
        public int ENTIDAD_ID { get; set; }
        public byte SALUDO_ID { get; set; }
        public Nullable<byte> PROFESION_ID { get; set; }
    
        public virtual ENTIDADES ENTIDAD { get; set; }
        public virtual PERSONA_SALUDOS SALUDO { get; set; }
        public virtual PERSONA_PROFESIONES PROFESION { get; set; }
    }
}
