//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesContext : DbContext
    {
        public EntitiesContext()
            : base("name=EntitiesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CERCAS_CAPAS> CERCAS_CAPAS { get; set; }
        public virtual DbSet<CERCAS_CATS> CERCAS_CATS { get; set; }
        public virtual DbSet<REGIONES> REGIONES { get; set; }
        public virtual DbSet<CERCAS_CALZADAS> CERCAS_CALZADAS { get; set; }
        public virtual DbSet<CERCAS_CURVAS_GRADO> CERCAS_CURVAS_GRADO { get; set; }
        public virtual DbSet<CERCAS_CURVAS_TIPOS> CERCAS_CURVAS_TIPOS { get; set; }
        public virtual DbSet<CERCAS_TRAZADO_VIA> CERCAS_TRAZADO_VIA { get; set; }
        public virtual DbSet<CERCAS_CALZADAS_ESTADOS> CERCAS_CALZADAS_ESTADOS { get; set; }
        public virtual DbSet<CERCAS_PENDIENTES> CERCAS_PENDIENTES { get; set; }
        public virtual DbSet<CERCAS_PENDIENTES_GRADO> CERCAS_PENDIENTES_GRADO { get; set; }
        public virtual DbSet<CERCAS_TRAFICO> CERCAS_TRAFICO { get; set; }
        public virtual DbSet<CERCAS_FORMAS> CERCAS_FORMAS { get; set; }
        public virtual DbSet<CERCAS> CERCAS { get; set; }
        public virtual DbSet<CERCAS_PUNTOS> CERCAS_PUNTOS { get; set; }
        public virtual DbSet<CERCAS_ENRUTA> CERCAS_ENRUTA { get; set; }
        public virtual DbSet<SEGMENTOS> SEGMENTOS { get; set; }
        public virtual DbSet<SEGMENTOS_CATS> SEGMENTOS_CATS { get; set; }
        public virtual DbSet<TRAMOS> TRAMOS { get; set; }
        public virtual DbSet<TRAMOS_CATS> TRAMOS_CATS { get; set; }
        public virtual DbSet<TRAMOS_SEGMENTOS> TRAMOS_SEGMENTOS { get; set; }
        public virtual DbSet<RUTAS> RUTAS { get; set; }
        public virtual DbSet<RUTAS_CATS> RUTAS_CATS { get; set; }
        public virtual DbSet<RUTAS_TRAMOS> RUTAS_TRAMOS { get; set; }
        public virtual DbSet<SEGMENTOS_CERCAS> SEGMENTOS_CERCAS { get; set; }
        public virtual DbSet<EQUIPOS_GRUPOS> EQUIPOS_GRUPOS { get; set; }
        public virtual DbSet<EQUIPOS_CATS> EQUIPOS_CATS { get; set; }
        public virtual DbSet<EQUIPOS> EQUIPOS { get; set; }
        public virtual DbSet<GPS> GPS { get; set; }
        public virtual DbSet<EQUIPOS_ESTADOS_OPERA> EQUIPOS_ESTADOS_OPERA { get; set; }
        public virtual DbSet<ENTIDADES_CATS> ENTIDADES_CATS { get; set; }
        public virtual DbSet<ENTIDADES_IDENT_TIPOS> ENTIDADES_IDENT_TIPOS { get; set; }
        public virtual DbSet<ENTIDADES_RELS> ENTIDADES_RELS { get; set; }
        public virtual DbSet<ENTIDADES_TIPOS> ENTIDADES_TIPOS { get; set; }
        public virtual DbSet<EMAIL_PROPS> EMAIL_PROPS { get; set; }
        public virtual DbSet<EMAIL_TIPOS> EMAIL_TIPOS { get; set; }
        public virtual DbSet<PERSONA_PROFESIONES> PERSONA_PROFESIONES { get; set; }
        public virtual DbSet<PERSONA_SALUDOS> PERSONA_SALUDOS { get; set; }
        public virtual DbSet<TELEFONO_TIPOS> TELEFONO_TIPOS { get; set; }
        public virtual DbSet<UNIDADES> UNIDADES { get; set; }
        public virtual DbSet<CIUDADES> CIUDADES { get; set; }
        public virtual DbSet<ENTIDADES_DIRS_TIPOS> ENTIDADES_DIRS_TIPOS { get; set; }
        public virtual DbSet<PAISES> PAISES { get; set; }
        public virtual DbSet<PROVINCIAS> PROVINCIAS { get; set; }
        public virtual DbSet<PRODUCTOS_CATS> PRODUCTOS_CATS { get; set; }
        public virtual DbSet<ALARMAS_NIVELES> ALARMAS_NIVELES { get; set; }
        public virtual DbSet<ALARMAS_PERMANS> ALARMAS_PERMANS { get; set; }
        public virtual DbSet<ALARMAS_PERMANS_RESETS> ALARMAS_PERMANS_RESETS { get; set; }
        public virtual DbSet<ALARMAS_UNIDADES> ALARMAS_UNIDADES { get; set; }
        public virtual DbSet<RUTAS_OPERAS> RUTAS_OPERAS { get; set; }
        public virtual DbSet<EQUIPOS_CAPS> EQUIPOS_CAPS { get; set; }
        public virtual DbSet<EQUIPOS_CAPS_REL> EQUIPOS_CAPS_REL { get; set; }
        public virtual DbSet<ENTIDADES> ENTIDADES { get; set; }
        public virtual DbSet<ENTIDADES_CATS_REL> ENTIDADES_CATS_REL { get; set; }
        public virtual DbSet<ALARMAS_CATS> ALARMAS_CATS { get; set; }
        public virtual DbSet<ALARMAS> ALARMAS { get; set; }
        public virtual DbSet<ENTIDADES_RELS_REL> ENTIDADES_RELS_REL { get; set; }
        public virtual DbSet<ENTIDADES_DIRS> ENTIDADES_DIRS { get; set; }
        public virtual DbSet<ALARMAS_NIVELES_REL> ALARMAS_NIVELES_REL { get; set; }
        public virtual DbSet<MARCAS> MARCAS { get; set; }
        public virtual DbSet<MARCAS_CATS> MARCAS_CATS { get; set; }
        public virtual DbSet<MODELOS> MODELOS { get; set; }
        public virtual DbSet<ENTIDADES_DIRS_TIPOS_REL> ENTIDADES_DIRS_TIPOS_REL { get; set; }
        public virtual DbSet<ENTIDADES_AREAS> ENTIDADES_AREAS { get; set; }
        public virtual DbSet<ENTIDADES_CTOS> ENTIDADES_CTOS { get; set; }
        public virtual DbSet<ENTIDADES_TELFS> ENTIDADES_TELFS { get; set; }
        public virtual DbSet<ENTIDADES_CARGOS> ENTIDADES_CARGOS { get; set; }
        public virtual DbSet<ENTIDADES_DIRS_CTOS_REL> ENTIDADES_DIRS_CTOS_REL { get; set; }
        public virtual DbSet<ENTIDADES_PERSONA> ENTIDADES_PERSONA { get; set; }
        public virtual DbSet<ENTIDADES_EMAILS> ENTIDADES_EMAILS { get; set; }
        public virtual DbSet<ENTIDADES_EMAILS_PROPS> ENTIDADES_EMAILS_PROPS { get; set; }
        public virtual DbSet<ENTIDADES_DIRS_UBICAS> ENTIDADES_DIRS_UBICAS { get; set; }
        public virtual DbSet<ENTIDADES_DIRS_UBICAS_TIPOS> ENTIDADES_DIRS_UBICAS_TIPOS { get; set; }
        public virtual DbSet<ENTIDADES_DIRS_UBICAS_TIPOSREL> ENTIDADES_DIRS_UBICAS_TIPOSREL { get; set; }
        public virtual DbSet<DIAS_TIPOS> DIAS_TIPOS { get; set; }
        public virtual DbSet<ENTIDADES_CALENDS> ENTIDADES_CALENDS { get; set; }
        public virtual DbSet<ENTIDADES_CALENDS_DIA_HRS> ENTIDADES_CALENDS_DIA_HRS { get; set; }
        public virtual DbSet<ENTIDADES_CALENDS_DIAS> ENTIDADES_CALENDS_DIAS { get; set; }
        public virtual DbSet<ENTIDADES_CALENDS_HRS> ENTIDADES_CALENDS_HRS { get; set; }
        public virtual DbSet<EVENTOS> EVENTOS { get; set; }
        public virtual DbSet<GPS_MONI_ESTADO> GPS_MONI_ESTADO { get; set; }
        public virtual DbSet<GPS_REPORTES> GPS_REPORTES { get; set; }
        public virtual DbSet<VW_ALARMAS_LOG> VW_ALARMAS_LOG { get; set; }
        public virtual DbSet<GPS_ALARMAS> GPS_ALARMAS { get; set; }
        public virtual DbSet<GPS_EVENTOS> GPS_EVENTOS { get; set; }
        public virtual DbSet<RUTAS_FASES> RUTAS_FASES { get; set; }
        public virtual DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public virtual DbSet<FRENTES> FRENTES { get; set; }
        public virtual DbSet<VIAJES_ESTADO> VIAJES_ESTADO { get; set; }
        public virtual DbSet<VIAJES> VIAJES { get; set; }
        public virtual DbSet<VIAJES_CONDUCTORES> VIAJES_CONDUCTORES { get; set; }
        public virtual DbSet<VIAJES_RUTAS> VIAJES_RUTAS { get; set; }
        public virtual DbSet<RUTAS_FASES_REL> RUTAS_FASES_REL { get; set; }
        public virtual DbSet<GPS_ALARMAS_OCURRS> GPS_ALARMAS_OCURRS { get; set; }
        public virtual DbSet<VW_ALARMAS_SUMARIO> VW_ALARMAS_SUMARIO { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<VIAJES_CONTACTOS> VIAJES_CONTACTOS { get; set; }
        public virtual DbSet<TRAYECTOS> TRAYECTOS { get; set; }
        public virtual DbSet<TRAYECTOS_RUTAS> TRAYECTOS_RUTAS { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<ROLES_PERMISOS> ROLES_PERMISOS { get; set; }
        public virtual DbSet<PERMISOS_REQUERIDOS> PERMISOS_REQUERIDOS { get; set; }
        public virtual DbSet<PERMISOS_REQUERIDOS_ACCS> PERMISOS_REQUERIDOS_ACCS { get; set; }
        public virtual DbSet<PERMISOS_REQUERIDOS_ROLES> PERMISOS_REQUERIDOS_ROLES { get; set; }
        public virtual DbSet<ENTIDADES_NOTIF_ALARMAS> ENTIDADES_NOTIF_ALARMAS { get; set; }
        public virtual DbSet<ENTIDADES_NOTIF_ALARMAS_DIRS> ENTIDADES_NOTIF_ALARMAS_DIRS { get; set; }
        public virtual DbSet<ENTIDADES_NOTIF_ALARMAS_EMS> ENTIDADES_NOTIF_ALARMAS_EMS { get; set; }
        public virtual DbSet<ALARMAS_GRADOS> ALARMAS_GRADOS { get; set; }
        public virtual DbSet<ALARMAS_VELOCIDAD> ALARMAS_VELOCIDAD { get; set; }
        public virtual DbSet<ALARMAS_VELOCIDAD_RANG> ALARMAS_VELOCIDAD_RANG { get; set; }
        public virtual DbSet<ALARMAS_VELOCIDAD_RANG_TIEM> ALARMAS_VELOCIDAD_RANG_TIEM { get; set; }
    }
}
