//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADES_DIRS_UBICAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTIDADES_DIRS_UBICAS()
        {
            this.HIJOS = new HashSet<ENTIDADES_DIRS_UBICAS>();
            this.TIPOS = new HashSet<ENTIDADES_DIRS_UBICAS_TIPOSREL>();
            this.TELEFONOS = new HashSet<ENTIDADES_TELFS>();
        }
    
        public int ID { get; set; }
        public int ENTIDAD_ID { get; set; }
        public int DIRECCION_ID { get; set; }
        public string DESCRIPCION_LARGA { get; set; }
        public string DESCRIPCION_MED { get; set; }
        public string DESCRIPCION_CORTA { get; set; }
        public string ABREVIACION { get; set; }
        public byte ESTADO_ID { get; set; }
        public Nullable<int> CERCA_ID { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> UBICACION_ID { get; set; }
    
        public virtual CERCAS CERCA { get; set; }
        public virtual ENTIDADES ENTIDAD { get; set; }
        public virtual ENTIDADES_DIRS DIRECCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_DIRS_UBICAS> HIJOS { get; set; }
        public virtual ENTIDADES_DIRS_UBICAS PADRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_DIRS_UBICAS_TIPOSREL> TIPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_TELFS> TELEFONOS { get; set; }
    }
}
