//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADES_NOTIF_ALARMAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTIDADES_NOTIF_ALARMAS()
        {
            this.LUGARES = new HashSet<ENTIDADES_NOTIF_ALARMAS_DIRS>();
            this.EMAILS = new HashSet<ENTIDADES_NOTIF_ALARMAS_EMS>();
        }
    
        public int ID { get; set; }
        public int ENTIDAD_ID { get; set; }
        public int PERSONA_ID { get; set; }
        public Nullable<short> ALARMAS_ROL_ID { get; set; }
    
        public virtual ENTIDADES EMPRESA { get; set; }
        public virtual ENTIDADES PERSONA { get; set; }
        public virtual ROLES ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_NOTIF_ALARMAS_DIRS> LUGARES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_NOTIF_ALARMAS_EMS> EMAILS { get; set; }
    }
}
