//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTIDADES()
        {
            this.CATS_RELS = new HashSet<ENTIDADES_CATS_REL>();
            this.RELS_REL = new HashSet<ENTIDADES_RELS_REL>();
            this.DIRECCIONES = new HashSet<ENTIDADES_DIRS>();
            this.CTOS_EMPRESA = new HashSet<ENTIDADES_CTOS>();
            this.CTOS_PERSONA = new HashSet<ENTIDADES_CTOS>();
            this.TELEFONOS = new HashSet<ENTIDADES_TELFS>();
            this.EMAILS = new HashSet<ENTIDADES_EMAILS>();
            this.UBICACIONES = new HashSet<ENTIDADES_DIRS_UBICAS>();
            this.FRENTES = new HashSet<FRENTES>();
            this.VIAJES = new HashSet<VIAJES>();
            this.VIAJES_CONDUCTORES = new HashSet<VIAJES_CONDUCTORES>();
            this.RUTAS_FASES_REL = new HashSet<RUTAS_FASES_REL>();
            this.USUARIOS = new HashSet<USUARIOS>();
            this.ENTIDADES_NOTIF_ALARMAS = new HashSet<ENTIDADES_NOTIF_ALARMAS>();
            this.ENTIDADES_NOTIF_ALARMAS1 = new HashSet<ENTIDADES_NOTIF_ALARMAS>();
        }
    
        public int ID { get; set; }
        public string DESCRIPCION_LARGA { get; set; }
        public string DESCRIPCION_MED { get; set; }
        public string DESCRIPCION_CORTA { get; set; }
        public string ABREVIACION { get; set; }
        public byte ESTADO_ID { get; set; }
        public byte TIPO_ID { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string APELLIDOS { get; set; }
        public string NOMBRES { get; set; }
        public Nullable<byte> IDENT_TIPO_ID { get; set; }
        public string IDENTIFICACION { get; set; }
        public string CLASIFICADOR { get; set; }
        public string ALTERNO_ID { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual ENTIDADES_TIPOS TIPO { get; set; }
        public virtual ENTIDADES_IDENT_TIPOS IDENT_TIPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_CATS_REL> CATS_RELS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_RELS_REL> RELS_REL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_DIRS> DIRECCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_CTOS> CTOS_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_CTOS> CTOS_PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_TELFS> TELEFONOS { get; set; }
        public virtual ENTIDADES_PERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_EMAILS> EMAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_DIRS_UBICAS> UBICACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRENTES> FRENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIAJES> VIAJES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIAJES_CONDUCTORES> VIAJES_CONDUCTORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RUTAS_FASES_REL> RUTAS_FASES_REL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_NOTIF_ALARMAS> ENTIDADES_NOTIF_ALARMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_NOTIF_ALARMAS> ENTIDADES_NOTIF_ALARMAS1 { get; set; }
    }
}
