//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADES_RELS_REL
    {
        public int ENTIDAD_ID { get; set; }
        public byte RELACION_ID { get; set; }
        public byte ORDEN { get; set; }
    
        public virtual ENTIDADES ENTIDADES { get; set; }
        public virtual ENTIDADES_RELS ENTIDADES_RELS { get; set; }
    }
}
