//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADES_DIRS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTIDADES_DIRS()
        {
            this.TIPOS_REL = new HashSet<ENTIDADES_DIRS_TIPOS_REL>();
            this.CONTACTOS_REL = new HashSet<ENTIDADES_DIRS_CTOS_REL>();
            this.UBICACIONES = new HashSet<ENTIDADES_DIRS_UBICAS>();
            this.TELEFONOS = new HashSet<ENTIDADES_TELFS>();
            this.ENTIDADES_NOTIF_ALARMAS_DIRS = new HashSet<ENTIDADES_NOTIF_ALARMAS_DIRS>();
        }
    
        public int ID { get; set; }
        public int ENTIDAD_ID { get; set; }
        public int PAIS_ID { get; set; }
        public Nullable<byte> REGION_ID { get; set; }
        public Nullable<int> PROVINCIA_ID { get; set; }
        public Nullable<int> CIUDAD_ID { get; set; }
        public string CODIGOPOSTAL { get; set; }
        public string CALLE_PRINCIPAL { get; set; }
        public string NUMERACION { get; set; }
        public string CALLE_TRANSVERSAL { get; set; }
        public Nullable<int> CERCA_ID { get; set; }
        public string OBSERVACIONES { get; set; }
        public string CANTON { get; set; }
        public string CIUDADELA { get; set; }
        public string MANZANA { get; set; }
        public string DESCRIPCION_LARGA { get; set; }
        public string DESCRIPCION_MED { get; set; }
        public string DESCRIPCION_CORTA { get; set; }
        public string ABREVIACION { get; set; }
        public byte ESTADO_ID { get; set; }
    
        public virtual CIUDADES CIUDAD { get; set; }
        public virtual ENTIDADES ENTIDAD { get; set; }
        public virtual PAISES PAIS { get; set; }
        public virtual PROVINCIAS PROVINCIA { get; set; }
        public virtual CERCAS CERCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_DIRS_TIPOS_REL> TIPOS_REL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_DIRS_CTOS_REL> CONTACTOS_REL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_DIRS_UBICAS> UBICACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_TELFS> TELEFONOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_NOTIF_ALARMAS_DIRS> ENTIDADES_NOTIF_ALARMAS_DIRS { get; set; }
    }
}
