//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADES_CTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTIDADES_CTOS()
        {
            this.DIRECCIONES_REL = new HashSet<ENTIDADES_DIRS_CTOS_REL>();
            this.VIAJES_CONTACTOS = new HashSet<VIAJES_CONTACTOS>();
        }
    
        public int ID { get; set; }
        public byte ESTADO_ID { get; set; }
        public string OBSERVACIONES { get; set; }
        public short CARGO_ID { get; set; }
        public short AREA_ID { get; set; }
        public string FUNCION { get; set; }
        public int EMPRESA_ID { get; set; }
        public int PERSONA_ID { get; set; }
    
        public virtual ENTIDADES EMPRESA { get; set; }
        public virtual ENTIDADES PERSONA { get; set; }
        public virtual ENTIDADES_AREAS AREA { get; set; }
        public virtual ENTIDADES_CARGOS CARGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADES_DIRS_CTOS_REL> DIRECCIONES_REL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIAJES_CONTACTOS> VIAJES_CONTACTOS { get; set; }
    }
}
