//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUIPOS()
        {
            this.GPS = new HashSet<GPS>();
            this.CAPACIDADES = new HashSet<EQUIPOS_CAPS_REL>();
            this.VIAJES = new HashSet<VIAJES>();
        }
    
        public int ID { get; set; }
        public string DESCRIPCION_LARGA { get; set; }
        public string DESCRIPCION_MED { get; set; }
        public string DESCRIPCION_CORTA { get; set; }
        public string ABREVIACION { get; set; }
        public byte ESTADO_OPERA_ID { get; set; }
        public byte GRUPO_ID { get; set; }
        public short CATEGORIA_ID { get; set; }
        public string PLACA { get; set; }
        public short MODELO_ID { get; set; }
        public short MODELO_ANO { get; set; }
        public byte ESTADO_ID { get; set; }
        public string ALTERNO_ID { get; set; }
        public short MARCA_ID { get; set; }
        public string SERIAL { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual EQUIPOS_CATS CATEGORIA { get; set; }
        public virtual EQUIPOS_GRUPOS GRUPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPS> GPS { get; set; }
        public virtual EQUIPOS_ESTADOS_OPERA ESTADO_OPERACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPOS_CAPS_REL> CAPACIDADES { get; set; }
        public virtual MARCAS MARCA { get; set; }
        public virtual MODELOS MODELO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIAJES> VIAJES { get; set; }
    }
}
