//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPOS_CAPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUIPOS_CAPS()
        {
            this.HIJOS = new HashSet<EQUIPOS_CAPS>();
            this.RELS = new HashSet<EQUIPOS_CAPS_REL>();
        }
    
        public short ID { get; set; }
        public string DESCRIPCION_LARGA { get; set; }
        public string DESCRIPCION_MED { get; set; }
        public string DESCRIPCION_CORTA { get; set; }
        public string ABREVIACION { get; set; }
        public byte ESTADO_ID { get; set; }
        public Nullable<short> PADRE_ID { get; set; }
        public short UNIDAD_ID { get; set; }
        public string OBSERVACIONES { get; set; }
        public string ORDENADOR { get; set; }
    
        public virtual UNIDADES UNIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPOS_CAPS> HIJOS { get; set; }
        public virtual EQUIPOS_CAPS PADRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPOS_CAPS_REL> RELS { get; set; }
    }
}
