//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPOS_CAPS_REL
    {
        public int EQUIPO_ID { get; set; }
        public short PRODUCTO_CATEGORIA_ID { get; set; }
        public short CAPACIDAD_ID { get; set; }
        public double VALOR { get; set; }
    
        public virtual EQUIPOS EQUIPO { get; set; }
        public virtual EQUIPOS_CAPS CAPACIDAD { get; set; }
        public virtual PRODUCTOS_CATS PRODUCTO_CATEGORIA { get; set; }
    }
}
