//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPS_REPORTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GPS_REPORTES()
        {
            this.GPS_MONI_ESTADO = new HashSet<GPS_MONI_ESTADO>();
        }
    
        public long ID { get; set; }
        public double LAT { get; set; }
        public double LNG { get; set; }
        public short ALTURA { get; set; }
        public double VELOCIDAD { get; set; }
        public byte ARRANQUE_ESTADO { get; set; }
        public byte MOVIMIENTO_ESTADO { get; set; }
        public System.DateTime ENVIO_FECHAHORA { get; set; }
        public System.DateTime REGISTRO_FECHAHORA { get; set; }
        public int GPS_ID { get; set; }
        public Nullable<int> VIAJE_RUTA_ID { get; set; }
        public Nullable<int> VIAJE_ID { get; set; }
        public Nullable<int> RUTA_ID { get; set; }
        public Nullable<int> TRAMO_ID { get; set; }
        public Nullable<int> SEGMENTO_ID { get; set; }
        public Nullable<int> CERCA_ID { get; set; }
        public Nullable<int> CONDUCTOR_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPS_MONI_ESTADO> GPS_MONI_ESTADO { get; set; }
    }
}
