//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPS_ALARMAS
    {
        public long ID { get; set; }
        public long REPORTE_ID { get; set; }
        public Nullable<long> REPORTE_FIN_ID { get; set; }
        public int GPS_ID { get; set; }
        public int EQUIPO_ID { get; set; }
        public int VIAJE_ID { get; set; }
        public Nullable<int> CERCA_ID { get; set; }
        public short ALARMA_ID { get; set; }
        public System.DateTime FECHAHORA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHAHORA_FIN { get; set; }
        public int DURACION { get; set; }
        public double VALOR_STANDARD { get; set; }
        public double VALOR_EFECTIVO { get; set; }
        public double VALOR_MAXIMO { get; set; }
    
        public virtual ALARMAS ALARMA { get; set; }
        public virtual CERCAS CERCA { get; set; }
    }
}
