//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPS_EVENTOS
    {
        public long ID { get; set; }
        public int GPS_ID { get; set; }
        public int VIAJE_ID { get; set; }
        public int EQUIPO_ID { get; set; }
        public short EVENTO_ID { get; set; }
        public byte EVENTO_ESTADO { get; set; }
        public Nullable<int> CERCA_ID { get; set; }
        public long REPORTE_ID { get; set; }
        public System.DateTime FECHAHORA { get; set; }
        public Nullable<long> GPS_EVENTO_ID { get; set; }
        public int DURACION { get; set; }
        public Nullable<int> REL_ID { get; set; }
        public Nullable<int> RUTA_ID { get; set; }
    
        public virtual CERCAS CERCA { get; set; }
        public virtual EVENTOS EVENTO { get; set; }
    }
}
