//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPS_ALARMAS_OCURRS
    {
        public int GPS_ID { get; set; }
        public int EQUIPO_ID { get; set; }
        public int VIAJE_ID { get; set; }
        public int RUTA_ID { get; set; }
        public byte NIVEL { get; set; }
        public int NIVEL_REL_ID { get; set; }
        public short ALARMA_ID { get; set; }
        public short OCURRENCIAS { get; set; }
    
        public virtual GPS GPS { get; set; }
    }
}
