//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPS_MONI_ESTADO
    {
        public int GPS_ID { get; set; }
        public Nullable<int> VIAJE_ID { get; set; }
        public Nullable<int> CERCA_ID { get; set; }
        public byte ESTADO_ID { get; set; }
        public Nullable<long> REPORTE_ID { get; set; }
        public Nullable<System.DateTime> FECHAHORA_IDLING { get; set; }
        public Nullable<int> RUTA_ID { get; set; }
        public Nullable<short> RUTA_INDICE { get; set; }
    
        public virtual CERCAS CERCA { get; set; }
        public virtual GPS GPS { get; set; }
        public virtual GPS_REPORTES REPORTE { get; set; }
        public virtual VIAJES VIAJE { get; set; }
    }
}
