//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES_PERMISOS
    {
        public short ROL_ID { get; set; }
        public int ELEMENTO_ID { get; set; }
        public Nullable<byte> DUMMY { get; set; }
        public short PERMISO_TIPO_ID { get; set; }
        public byte ACCION_ID { get; set; }
    
        public virtual ROLES ROLE { get; set; }
    }
}
