//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUTAS_TRAMOS
    {
        public int RUTA_ID { get; set; }
        public int TRAMO_ID { get; set; }
        public Nullable<short> ORDEN { get; set; }
    
        public virtual RUTAS RUTA { get; set; }
        public virtual TRAMOS TRAMO { get; set; }
    }
}
