//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUTAS_FASES_REL
    {
        public int RUTA_ID { get; set; }
        public int ENTIDAD_ID { get; set; }
        public byte TIPO_ID { get; set; }
        public int REL_ID { get; set; }
        public byte FASE_ID { get; set; }
    
        public virtual ENTIDADES ENTIDAD { get; set; }
        public virtual RUTAS RUTA { get; set; }
        public virtual RUTAS_FASES FASE { get; set; }
    }
}
