//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGMENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEGMENTOS()
        {
            this.TRAMO_SEGMENTOS = new HashSet<TRAMOS_SEGMENTOS>();
            this.SEGMENTO_CERCAS = new HashSet<SEGMENTOS_CERCAS>();
        }
    
        public int ID { get; set; }
        public string AUXILIAR_ID { get; set; }
        public string DESCRIPCION_LARGA { get; set; }
        public string DESCRIPCION_MED { get; set; }
        public string DESCRIPCION_CORTA { get; set; }
        public string ABREVIACION { get; set; }
        public byte ESTADO_ID { get; set; }
        public short CATEGORIA_ID { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual SEGMENTOS_CATS CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAMOS_SEGMENTOS> TRAMO_SEGMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEGMENTOS_CERCAS> SEGMENTO_CERCAS { get; set; }
    }
}
