//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGMENTOS_CERCAS
    {
        public int SEGMENTO_ID { get; set; }
        public int CERCA_ID { get; set; }
        public short ORDEN { get; set; }
    
        public virtual CERCAS CERCA { get; set; }
        public virtual SEGMENTOS SEGMENTO { get; set; }
    }
}
