//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int ID { get; set; }
        public string USUARIO { get; set; }
        public string CLAVE { get; set; }
        public short ROL_ID { get; set; }
        public Nullable<int> ENTIDAD_ID { get; set; }
    
        public virtual ENTIDADES ENTIDAD { get; set; }
        public virtual ROLES ROLE { get; set; }
    }
}
