//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIAJES_RUTAS
    {
        public int ID { get; set; }
        public int VIAJE_ID { get; set; }
        public int RUTA_ID { get; set; }
        public byte ORDEN { get; set; }
        public Nullable<System.DateTime> INICIO { get; set; }
        public Nullable<System.DateTime> FIN { get; set; }
    
        public virtual RUTAS RUTAS { get; set; }
        public virtual VIAJES VIAJES { get; set; }
    }
}
