//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIAJES_CONDUCTORES
    {
        public int VIAJE_ID { get; set; }
        public int ENTIDAD_ID { get; set; }
        public string DESDEPUNTO { get; set; }
        public string HASTAPUNTO { get; set; }
    
        public virtual ENTIDADES ENTIDADES { get; set; }
        public virtual VIAJES VIAJES { get; set; }
    }
}
