//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIAJES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VIAJES()
        {
            this.CONDUCTORES = new HashSet<VIAJES_CONDUCTORES>();
            this.RUTAS = new HashSet<VIAJES_RUTAS>();
            this.EQUIPOS = new HashSet<EQUIPOS>();
            this.GPS_MONI_ESTADO = new HashSet<GPS_MONI_ESTADO>();
            this.CONTACTOS = new HashSet<VIAJES_CONTACTOS>();
        }
    
        public int ID { get; set; }
        public int ENTIDAD_ID { get; set; }
        public string ORDEN_TRANSPORTE { get; set; }
        public short FRENTE_ID { get; set; }
        public byte ESTADO_ID { get; set; }
        public string ALTERNO_ID { get; set; }
        public System.DateTime INICIO { get; set; }
        public short PRODUCTO_ID { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual ENTIDADES ENTIDAD { get; set; }
        public virtual FRENTES FRENTE { get; set; }
        public virtual PRODUCTOS PRODUCTO { get; set; }
        public virtual VIAJES_ESTADO VIAJEESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIAJES_CONDUCTORES> CONDUCTORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIAJES_RUTAS> RUTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPOS> EQUIPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPS_MONI_ESTADO> GPS_MONI_ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIAJES_CONTACTOS> CONTACTOS { get; set; }
    }
}
