//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ALARMAS_SUMARIO
    {
        public int VIAJE_ID { get; set; }
        public byte NIVEL { get; set; }
        public string CATEGORIA { get; set; }
        public string CATEGORIA_ORDENADOR { get; set; }
        public string ALARMA { get; set; }
        public short OCURRENCIAS { get; set; }
        public short ALARMA_ID { get; set; }
    }
}
