//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSMonitoreo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ALARMAS_LOG
    {
        public string CATEGORIA { get; set; }
        public string CATEGORIA_ORDENADOR { get; set; }
        public string ALARMA { get; set; }
        public string CERCA { get; set; }
        public System.DateTime INICIO { get; set; }
        public Nullable<System.DateTime> FIN { get; set; }
        public int DURACION { get; set; }
        public long ID { get; set; }
        public double VALOR_STANDARD { get; set; }
        public double VALOR_EFECTIVO { get; set; }
        public int VIAJE_ID { get; set; }
        public short ALARMA_ID { get; set; }
        public short ALARMA_CATEGORIA_ID { get; set; }
        public string RUTA_AUXILIAR_ID { get; set; }
        public string TRAMO_AUXILIAR_ID { get; set; }
        public string SEGMENTO_AUXILIAR_ID { get; set; }
        public string CERCA_AUXILIAR_ID { get; set; }
        public Nullable<int> CONDUCTOR_ID { get; set; }
        public string CONDUCTOR { get; set; }
    }
}
